vim and lint updates

diff --git a/bin/lint b/bin/lint
--- a/bin/lint
+++ b/bin/lint
@@ -92,10 +92,10 @@ cd $gitd
 #-----------------------------------
 # Build the application 
 #-----------------------------------
-go build ./...
-if [ $? -ne 0 ]; then
-	echo "build failed"
-fi
+#go build ./...
+#if [ $? -ne 0 ]; then
+#	echo "build failed"
+#fi
 
 #-----------------------------------
 # Execute the linters 
